# Generated by Django 5.0.1 on 2024-03-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0002_alter_auto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='dscMantenimiento',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
        migrations.AddField(
            model_name='auto',
            name='dscMotor',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
        migrations.AddField(
            model_name='auto',
            name='dscPiston',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
        migrations.AddField(
            model_name='auto',
            name='dscVolante',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagenMantenimiento',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagenMotor',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagenPiston',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagenVolante',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
    ]
