# Generated by Django 5.0.1 on 2024-03-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0003_auto_dscmantenimiento_auto_dscmotor_auto_dscpiston_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='dscAuto',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
    ]
