# Generated by Django 5.0.1 on 2024-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0005_auto_dscneumatico_auto_imagenneumatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='dscEstructura',
            field=models.CharField(default='Valor predeterminado', max_length=500),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagenEstructura',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
    ]
